version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo previous dev lambda version ${PREVIOUS_LAMDA_VERSION}
      - pip install pytest
      - pytest test/test.py
  post_build:
    commands:
      - echo Testing of ${BUILD_ENV} is completed on `date`
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" != 1 ]; then
          aws lambda update-alias --function-name ${FUNCTION_NAME} --name ${BUILD_ENV} --function-version $PREVIOUS_LAMDA_VERSION;
        fi